---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedoom
  namespace: kubedoom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-kubedoom
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: my-kubedoom
    spec:
      hostNetwork: true
      serviceAccountName: kubedoom
      containers:
        - image: storaxdev/kubedoom:0.5.0
          name: my-kubedoom
          ports:
          - containerPort: 5900
            protocol: TCP
            name: vnc
