---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: postgres-config
  labels: 
    app: postres
data:
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  POSTGRES_DB: testdatabase
  PGDATA: /var/lib/postgresql/data/pgdata
