---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rs-postgres
    spec:
      containers:
        - image: postgres:10.13
          name: dm-postgres
          ports:
            - containerPort: 5432 
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb 
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-storage-claime
