---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-postgres10.13.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-postgres10.13.1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rs-postgres10.13.1
    spec:
      containers:
        - image: postgres:10.13
          name: dm-postgres
          ports:
            - containerPort: 5432 
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi


